version: '3.9'

services:
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api-typescript
    ports: 
      - "3005:3005"
    volumes:
      - ./:/usr/src/smart-brain-api-typescript
    environment:
      POSTGRES_URI: postgres://useruser:password@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    env_file:
      - ./.env
    links:
      - postgres
  
  postgres:
    container_name: database
    build: ./postgres
    restart: always
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: useruser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
  
  redis:
    image: redis
    ports:
      - "6379:6379"